# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.58.0
  hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          - --args=-write=true
          - --args=-recursive
      - id: terraform_docs
        args:
          - --hook-config=--create-file-if-not-exist=true
